FROM satijalab/seurat:5.0.0

LABEL maintainer="Anish Tatke CMI Lab <anish.tatke@medicine.ufl.edu>"

ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
ENV PYTHONUNBUFFERED=1

# OS deps
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      git wget curl ca-certificates unzip \
      build-essential cmake autoconf automake libtool pkg-config \
      libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev \
      libffi-dev liblzma-dev tk-dev uuid-dev \
      libcurl4-openssl-dev libexpat1-dev libhdf5-dev libpython3-dev \
      libv8-dev libglpk-dev libgsl-dev libpcre2-dev libudunits2-dev \
      libgdal-dev libpq-dev unixodbc unixodbc-dev \
      libfontconfig1-dev libcairo2-dev libharfbuzz-dev libfribidi-dev \
      libxml2-dev libxslt1-dev libzstd-dev \
      libmagick++-dev \
      memcached \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


# Python 3.12
ENV PY312_PREFIX=/opt/python312
RUN curl -sSLO https://www.python.org/ftp/python/3.12.8/Python-3.12.8.tgz && \
    tar -xzf Python-3.12.8.tgz && \
    cd Python-3.12.8 && \
    ./configure --prefix=${PY312_PREFIX} --with-ensurepip=install && \
    make -j"$(nproc)" && \
    make install && \
    cd / && rm -rf Python-3.12.8 Python-3.12.8.tgz

ENV PATH="${PY312_PREFIX}/bin:${PATH}"
RUN python3.12 -m pip install -U pip setuptools wheel && \
    ln -sfn ${PY312_PREFIX}/bin/python3.12 /usr/local/bin/python && \
    ln -sfn ${PY312_PREFIX}/bin/pip3.12 /usr/local/bin/pip && \
    python -V && python -m pip -V

# HDF5 LZF filter
WORKDIR /lzf
RUN set -eux; \
    mkdir -p /lzf/lzf; \
    wget -q https://raw.githubusercontent.com/h5py/h5py/3.0.0/lzf/lzf_filter.c \
            https://raw.githubusercontent.com/h5py/h5py/3.0.0/lzf/lzf_filter.h; \
    wget -q -P /lzf/lzf \
            https://raw.githubusercontent.com/h5py/h5py/3.0.0/lzf/lzf/lzf_c.c \
            https://raw.githubusercontent.com/h5py/h5py/3.0.0/lzf/lzf/lzf_d.c \
            https://raw.githubusercontent.com/h5py/h5py/3.0.0/lzf/lzf/lzfP.h \
            https://raw.githubusercontent.com/h5py/h5py/3.0.0/lzf/lzf/lzf.h; \
    gcc -O2 -fPIC -shared /lzf/lzf/*.c /lzf/lzf_filter.c \
        -I /usr/include/hdf5/serial/ -lhdf5_serial \
        -o /lzf/liblzf_filter.so

ENV HDF5_PLUGIN_PATH=/lzf
WORKDIR /


# R installs (single script, one RUN for better caching)
COPY Visium_Analysis/scripts/install_R_packages.r /tmp/install_R_packages.r
RUN Rscript /tmp/install_R_packages.r && rm -f /tmp/install_R_packages.r

RUN R -e 'remotes::install_github("satijalab/azimuth", dependencies = TRUE, upgrade = "never")'
RUN R -e 'remotes::install_github("ctlab/fgsea",dependencies=TRUE)'
RUN R -e 'remotes::install_github("JEFworks-Lab/STdeconvolve",dependencies=TRUE)'

# Helpful defaults
ENV build_path=/opt/build